from __future__ import annotations
from copyreg import pickle
import json
import tempfile
import textwrap
from flask import Flask, request, jsonify, send_file, abort
from io import BytesIO
from flask_cors import CORS
import os, re, sys, signal, shutil
from pathlib import Path
from datetime import datetime, timezone
import geopandas as gpd
from flask import send_from_directory, abort
import osmnx as ox
import matplotlib
import pandas as pd
import numpy as np
import cv2
import subprocess
import rasterio
import threading
import json as jsonlib

from ai_settings import (
    ChatError,
    get_public_settings,
    list_provider_models,
    run_chat,
    update_settings,
)

worker_proc = None
worker_lock = threading.Lock()
worker_python_exe = None

app = Flask(__name__)
CORS(app)

DATA_DIR = Path("data")        
OUT_DIR  = Path("data/served")
vector_subdir = Path(OUT_DIR / "vector")
raster_subdir = Path(OUT_DIR / "raster")
metric_subdir = Path(OUT_DIR / "metric")
OUT_DIR.mkdir(parents=True, exist_ok=True)
vector_subdir.mkdir(parents=True, exist_ok=True)
raster_subdir.mkdir(parents=True, exist_ok=True)
metric_subdir.mkdir(parents=True, exist_ok=True)

CHART_TYPE_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")

# Chart Studio "Publish" writes generated chart components directly into
# frontend source (dev only - see docker-compose.dev.yml's frontend_src
# mount on the backend service; production has no such mount, checked at
# publish time). The manifest lives outside OUT_DIR so it survives the
# shutil.rmtree(OUT_DIR) that runs on every backend start/reload below.
FRONTEND_SRC_DIR = Path("/app/frontend_src")
FRONTEND_CHARTS_DIR = FRONTEND_SRC_DIR / "charts"
# Published chart components are generated here; the shared rendering
# engines (genericChartRenderer, customD3Renderer, vegaLite*) live one
# level up in charts/renderers, imported via a relative "../renderers/..."
# path baked into every generated file - see _generate_chart_file().
FRONTEND_CHARTS_GENERATED_DIR = FRONTEND_CHARTS_DIR / "generated"
CHART_MANIFEST_PATH = DATA_DIR / "chart_manifest.json"
CHART_REGISTRY_FILENAME = "customChartRegistry.generated.ts"
# Files a generated chart's name must not collide with (case-insensitively).
# bar/pie/table are ordinary published chart types, not special-cased -
# only genuinely load-bearing hand-written infrastructure is protected here.
RESERVED_CHART_FILES = {
    "renderComparison.tsx", "customD3Renderer.tsx", "genericChartRenderer.tsx",
    "vegaLiteRuntime.ts", "vegaLiteRenderer.tsx", "chartTypes.ts", CHART_REGISTRY_FILENAME,
}


def _pascal_case(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[-_]+", name) if p)


def _atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _load_chart_manifest() -> dict:
    if not CHART_MANIFEST_PATH.exists():
        return {}
    try:
        return json.loads(CHART_MANIFEST_PATH.read_text())
    except json.JSONDecodeError:
        return {}


def _save_chart_manifest(manifest: dict) -> None:
    _atomic_write_text(CHART_MANIFEST_PATH, json.dumps(manifest, indent=2))


def _generate_chart_file(render_fn_name: str, code: str, engine: str) -> str:
    if engine == "vega-lite":
        # code is already validated as parseable JSON by the caller. Embed it
        # as JSON.parse("<escaped text>") rather than a raw JS object literal -
        # a spec with a top-level key literally named "__proto__" behaves
        # differently as a re-parsed JSON string (an own data property, safe)
        # vs. a JS object literal (sets the object's prototype instead). This
        # makes the generated file byte-for-byte equivalent to what the
        # author's editor held, regardless of key names.
        spec_obj = json.loads(code)
        spec_js_string_literal = json.dumps(json.dumps(spec_obj))
        return (
            "// @ts-nocheck\n"
            "// AUTO-GENERATED by Chart Studio (Vega-Lite). Edits here are overwritten on republish.\n"
            "import type { ChartRenderFn } from \"../renderers/genericChartRenderer\";\n"
            "import { renderVegaLiteSpec } from \"../renderers/vegaLiteRuntime\";\n\n"
            f"const SPEC = JSON.parse({spec_js_string_literal});\n\n"
            f"export const {render_fn_name}: ChartRenderFn = (container, data, params, d3, containerWidth) => {{\n"
            "  return renderVegaLiteSpec(container, SPEC, data, containerWidth);\n"
            "};\n"
        )

    indented_code = textwrap.indent(code.rstrip(), "  ")
    return (
        # @ts-nocheck: pasted D3/JS is arbitrary author code, not written
        # against this project's strict tsconfig (noImplicitAny on untyped
        # D3 callback params, noUnusedParameters when a chart doesn't need
        # every one of container/data/params/d3, etc.) - a genuine syntax
        # error still fails to parse and is not suppressed by this. The
        # ChartRenderFn annotation below is inert under @ts-nocheck (nothing
        # is actually checked against it) - it's kept anyway so every
        # generated chart file reads the same way, regardless of name.
        "// @ts-nocheck\n"
        "// AUTO-GENERATED by Chart Studio. Edits here are overwritten on republish.\n"
        "import type { ChartRenderFn } from \"../renderers/genericChartRenderer\";\n\n"
        f"export const {render_fn_name}: ChartRenderFn = (container, data, params, d3, containerWidth) => {{\n"
        "  container.innerHTML = \"\";\n"
        f"{indented_code}\n"
        "};\n"
    )


def _regenerate_chart_registry(manifest: dict) -> None:
    imports = [
        f'import {{ {rec["componentName"]} }} from "./{rec["componentFile"][:-3]}";'
        for rec in manifest.values()
    ]
    entries = [f"  {json.dumps(name)}: {rec['componentName']}," for name, rec in manifest.items()]
    content = (
        "// AUTO-GENERATED by Chart Studio publish. Do not edit by hand - regenerated\n"
        "// in full on every publish.\n"
        'import type { ChartRenderFn } from "../renderers/genericChartRenderer";\n'
        + ("\n" + "\n".join(imports) + "\n" if imports else "\n")
        + "\nexport const customChartRenderers: Record<string, ChartRenderFn> = {\n"
        + ("\n".join(entries) + "\n" if entries else "")
        + "};\n"
    )
    _atomic_write_text(FRONTEND_CHARTS_GENERATED_DIR / CHART_REGISTRY_FILENAME, content)


def _check_chart_name_collision(name: str, component_file: str, manifest: dict) -> str | None:
    cf_lower = component_file.lower()
    if cf_lower in {f.lower() for f in RESERVED_CHART_FILES}:
        return f"'{name}' would generate '{component_file}', which collides with an existing built-in file"
    for other_name, rec in manifest.items():
        if other_name == name:
            continue  # republishing the same chart overwrites itself - allowed
        if rec["componentFile"].lower() == cf_lower:
            return f"'{name}' collides with existing chart type '{other_name}' (both generate {component_file})"
    return None

def start_worker():
    global worker_proc, worker_python_exe

    if worker_proc is not None and worker_proc.poll() is None:
        # already running
        return

    project_dir = Path(__file__).parent
    python_exe = Path(sys.executable)

    if not python_exe.exists():
        python_exe = project_dir / "envs" / ("python.exe" if os.name == "nt" else "bin/python")

    if not python_exe.exists():
        raise RuntimeError(f"Python interpreter not found at: {python_exe}")

    worker_python_exe = python_exe

    worker_proc = subprocess.Popen(
        [str(python_exe), "-u", "python_worker.py"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        cwd=str(project_dir),
        env={**os.environ, "PYTHONPATH": str(project_dir) + os.pathsep + os.environ.get("PYTHONPATH", "")},
        bufsize=1,  # line-buffered
    )

    print("[WORKER] Started python_worker process PID:", worker_proc.pid)

def send_code_to_worker(code: str) -> dict:
    """
    Sends code to the persistent worker and returns a dict:
    { "ok": bool, "stdout": str, "stderr": str }
    """
    global worker_proc

    if worker_proc is None or worker_proc.poll() is not None:
        start_worker()

    with worker_lock:
        req = {"code": code}
        line = jsonlib.dumps(req) + "\n"

        assert worker_proc.stdin is not None
        worker_proc.stdin.write(line)
        worker_proc.stdin.flush()

        assert worker_proc.stdout is not None
        resp_line = worker_proc.stdout.readline()
        if not resp_line:
            raise RuntimeError("Worker process terminated unexpectedly")

    resp = jsonlib.loads(resp_line)
    return resp

# Remove cached outputs on exit
def cleanup_served():
    try:
        out_resolved = OUT_DIR.resolve()
        data_resolved = DATA_DIR.resolve()
        if data_resolved in out_resolved.parents and out_resolved.name == "served":
            if OUT_DIR.exists():
                shutil.rmtree(OUT_DIR, ignore_errors=True)
                print(f"[CLEANUP] Removed {OUT_DIR}")
        else:
            print(f"[CLEANUP] Refusing to remove unexpected path: {OUT_DIR}")
    except Exception as e:
        app.logger.error(f"[CLEANUP] Failed: {e}")

def register_cleanup_handlers():
    import atexit
    atexit.register(cleanup_served)

    def _handler(sig, frame):
        cleanup_served()
        sys.exit(0)

    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            signal.signal(sig, _handler)
        except Exception:
            pass

if os.environ.get("WERKZEUG_RUN_MAIN") == "true" or not app.debug:
    register_cleanup_handlers()

def resolve_feather_path(datafile: str, tag: str) -> Path:
    feather_filename = f"osm/processed/{datafile}/{tag}.feather"
    return DATA_DIR / feather_filename

def load_roi_mask(roi: dict) -> tuple[str, object]:
    rtype = roi.get("type")
    val = roi.get("value")
    if rtype == "bbox":
        xmin, ymin, xmax, ymax = map(float, val)
        return "bbox", (xmin, ymin, xmax, ymax)
    
    elif rtype == "geojson":
        roi_path = Path(val)
        roi_path = DATA_DIR / str(val)

        # Try this later in notebook and then add.. 

        # mask_gdf = gpd.read_file(roi_path)
        # mask = mask_gdf.union_all()
        # return "mask", gpd.GeoDataFrame(geometry=[mask], crs=mask_gdf.crs)

def crop_gdf(gdf: gpd.GeoDataFrame, roi_dict: dict) -> gpd.GeoDataFrame:
    roi_kind, roi = load_roi_mask(roi_dict)

    if roi_kind == "bbox":
        xmin, ymin, xmax, ymax = roi
        return gdf.cx[xmin:xmax, ymin:ymax]
    else:
        mask_gdf = roi  
        if mask_gdf.crs is None:
            mask_gdf = mask_gdf.set_crs(4326, allow_override=True)

        return gpd.clip(gdf, mask_gdf)
    
def select_features(gdf: gpd.GeoDataFrame, features: list[str]) -> gpd.GeoDataFrame:
    existing = [f for f in features if f in gdf.columns]
    cols = existing + (["geometry"] if "geometry" in gdf.columns else [])
    
    return gdf[cols]

@app.get("/api/list-rasters/<Id>")
def list_rasters(Id: str):
    """
    Return a JSON list of PNG raster tiles inside:
    data/served/raster/<Id>/
    """
    folder = raster_subdir / Id

    try:
        folder.resolve().relative_to(raster_subdir.resolve())
    except Exception:
        return jsonify({"error": "Invalid raster folder"}), 403

    if not folder.exists() or not folder.is_dir():
        return jsonify([]), 200   # return empty list

    files = [
        f.name
        for f in folder.iterdir()
        if f.is_file() and f.suffix.lower() == ".png"
    ]

    return jsonify(files), 200

@app.get("/generated/raster/<path:filename>")
def serve_raster(filename: str):
    allowed_exts = {"png", "tif", "tiff"}

    try:
      ext = filename.rsplit(".", 1)[1].lower()
    except IndexError:
      abort(404)

    if ext not in allowed_exts:
        abort(404)

    full_path = raster_subdir / filename
    try:
        full_path.resolve().relative_to(raster_subdir.resolve())
    except Exception:
        abort(403)  # Forbidden

    directory = full_path.parent
    file = full_path.name

    if ext == "png":
        mimetype = "image/png"
    else:  # tif / tiff
        mimetype = "image/tiff"

    return send_from_directory(
        directory,
        file,
        mimetype=mimetype,
        conditional=True,
    )

@app.get("/generated/vector/<path:filename>")
def serve_vector(filename: str):
    if not filename.lower().endswith(".geojson"):
        abort(404)

    return send_from_directory(
        vector_subdir,
        filename,
        mimetype="application/geo+json",
        conditional=True
    )

@app.post('/api/extract-data-layer')
def extract_data_layer():
    payload = request.get_json(silent=True) or {}
    pl = payload
    problems = []
    
    id = pl.get("id")
    src = pl.get("source")
    dtype = pl.get("dtype")

    # datafile = pl.get("datafile")
    roi = pl.get("roi") or {}
    roi_datafile = pl.get("roi").get("datafile")

    if(src == "osm"):
        for f in (pl.get("osm_features") or []):
            feature = f.get("feature")
            attributes = f.get("attributes") or []
            try:
                src_path = resolve_feather_path(str(roi_datafile), str(feature))
                if not src_path.is_file():
                    raise FileNotFoundError(f"Missing source: {src_path}")
                print(f"    Loading data from: {src_path}")
                gdf = gpd.read_feather(src_path)

                gdf_cut = crop_gdf(gdf, roi)
                gdf_out = select_features(gdf_cut, attributes)

                out_name = f"vector/{id}_{feature}.geojson"
                out_path = OUT_DIR / out_name
                
                gdf_out.to_file(out_path, driver="GeoJSON")

            except Exception as e:
                error_msg = f"[ERROR] Layer {id}:{feature} → {type(e).__name__}: {e}"
                print(error_msg)

                problems.append({
                    "data_layer_id": id,
                    "feature": feature,
                    "error": str(e)
                })

        return jsonify({
            "status": "success" if not problems else "partial",
            "problems": problems
        }), 200 if not problems else 207
    else:
        return jsonify({"status": "error", "error": f"Unsupported source: {src}"}), 400


@app.route("/api/update-data-layer", methods=["POST"])
def update_data_layer():
    data = request.get_json()
    ref = data["ref"]
    # tag = data["tag"]
    geojson = data["geojson"]

    filename = f"vector/{ref}.geojson"
    filepath = OUT_DIR / filename

    with open(filepath, "w") as f:
        json.dump(geojson, f)

    return jsonify({"status": "success"}), 200

@app.post("/api/run-python")
def run_python():
    payload = request.get_json() or {}
    code = payload.get("code", "")

    print("Received code to run:\n", code)

    try:
        resp = send_code_to_worker(code)
        # resp: {"ok": bool, "stdout": "...", "stderr": "..."}

        return jsonify({
            "stdout": resp.get("stdout", ""),
            "stderr": resp.get("stderr", ""),
            "returncode": 0 if resp.get("ok") else 1,
        }), 200

    except Exception as e:
        # If something goes really wrong (worker dead, etc.)
        return jsonify({
            "stdout": "",
            "stderr": f"Worker error: {e}",
            "returncode": -1,
        }), 200
    
COLORMAPS = {
    "viridis": matplotlib.colormaps.get_cmap("viridis"),
    "reds": matplotlib.colormaps.get_cmap("Reds"),
    "greens": matplotlib.colormaps.get_cmap("Greens"),
    "blues": matplotlib.colormaps.get_cmap("Blues"),
    "grays":   matplotlib.colormaps.get_cmap("Greys")
}

@app.get("/generated/raster/<ref>/<name>")
def get_colormapped_tile(ref, name):
    path = raster_subdir / ref / name

    cmap_name = (request.args.get("cmap") or "").lower()
    cmap = COLORMAPS.get(cmap_name)

    # If no/unknown colormap → return original PNG
    if cmap is None:
        return send_file(path, mimetype="image/png")

    # Read image (gray / BGR / BGRA)
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        abort(404)

    # ---- extract grayscale 0–255 ----
    if img.ndim == 2:
        gray = img.astype(np.float32)
        alpha = None
    elif img.shape[2] == 4:
        gray = img[:, :, 0].astype(np.float32)
        alpha = img[:, :, 3]
    else:
        gray = img[:, :, 0].astype(np.float32)
        alpha = None

    # ---- normalize FIXED 0–255 ----
    t = np.clip(gray / 255.0, 0.0, 1.0)

    # ---- apply matplotlib colormap ----
    rgba = (cmap(t) * 255).astype(np.uint8)  # H x W x 4

    # ---- preserve alpha if present ----
    if alpha is not None:
        rgba[:, :, 3] = alpha

    rgba = rgba[..., [2, 1, 0, 3]]  # RGBA -> BGRA for OpenCV

    ok, buf = cv2.imencode(".png", rgba)
    if not ok:
        abort(500)

    return send_file(BytesIO(buf.tobytes()), mimetype="image/png")
    
def diff_dirs(dir1_, dir2_):
    dir1 = Path(raster_subdir, dir1_)
    dir2 = Path(raster_subdir, dir2_)
    output_path = Path(raster_subdir, f"{dir1_}_minus_{dir2_}")

    if output_path.exists():
        shutil.rmtree(output_path)
    output_path.mkdir(parents=True, exist_ok=True)

    for png1 in sorted(dir1.glob("*.png")):
        png2 = dir2 / png1.name
        if not png2.exists():
            print(f"Skipping {png1.name}: not found in {dir2}")
            continue

        # Read as grayscale (single channel 0..255)
        gray1 = cv2.imread(str(png1), cv2.IMREAD_GRAYSCALE)
        gray2 = cv2.imread(str(png2), cv2.IMREAD_GRAYSCALE)

        if gray1 is None or gray2 is None:
            print(f"Skipping {png1.name}: failed to read one of the images")
            continue

        # absolute difference in 0..255 (uint8)
        diff_u8 = cv2.absdiff(gray2, gray1)

        # Save as grayscale PNG (no colormap baked in)
        cv2.imwrite(str(output_path / png1.name), diff_u8)

    return output_path

@app.route("/api/diff-png", methods=["POST"])
def api_diff_png():
    data = request.get_json(force=True)
    dir1 = data.get("dir1")
    dir2 = data.get("dir2")
    # colormap = data.get("colormap", "Reds")

    if not dir1 or not dir2:
        return jsonify({"error": "dir1 and dir2 are required"}), 400

    out_dir = diff_dirs(dir1, dir2)
    return jsonify({
        "status": "ok",
        "output_dir": str(out_dir),
    })

def diff_tif_files(tif1_name_, tif2_name_):

    tif1_name = tif1_name_ + ".tif"
    tif2_name = tif2_name_ + ".tif"

    tif1_path = Path(raster_subdir, tif1_name)
    tif2_path = Path(raster_subdir, tif2_name)

    out_name = f"{tif1_name_}_minus_{tif2_name_}.tif"
    out_path = Path(raster_subdir, out_name)

    with rasterio.open(tif1_path) as r1, rasterio.open(tif2_path) as r2:
        arr1 = r1.read(1).astype("float32")
        arr2 = r2.read(1).astype("float32")

        # Difference: scenario2 - scenario1
        diff = np.abs(arr2 - arr1)

        profile = r1.profile
        profile.update(
            dtype="float32",
            count=1,
        )

        with rasterio.open(out_path, "w", **profile) as dst:
            dst.write(diff, 1)

    return out_path

@app.route("/api/diff-tif", methods=["POST"])
def api_diff_tif():
    data = request.get_json(force=True)
    tif1 = data.get("tif1")
    tif2 = data.get("tif2")

    if not tif1 or not tif2:
        return jsonify({"error": "tif1 and tif2 are required"}), 400

    out_path = diff_tif_files(tif1, tif2)

    return jsonify({
        "status": "ok",
        "output_tif": str(out_path),
    })

def _as_field_list(value):
    """comparison grammar: x*/y* - a bare string is shorthand for a 1-item set."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


@app.post("/api/comparison-view")
def comparison_view():
    data = request.get_json(force=True)

    print("Received comparison view request:", data)
    key = data.get("key", [])
    x_fields = _as_field_list(data.get("x"))
    y_fields = _as_field_list(data.get("y"))
    chart = data.get("chart", "")
    props = data.get("props", {})

    if not key:
        return jsonify({"error": "key must be non-empty"}), 400

    fields = x_fields + y_fields
    if not fields:
        return jsonify({"error": "At least one field must be declared via x or y"}), 400

    axis = "x" if x_fields else "y"
    axis_label = fields[0]

    results = {}  # per scenario key: only the fields declared via x/y
    for k in key:
        csv_path = metric_subdir / f"{k}.csv"
        try:
            df = pd.read_csv(csv_path)
        except FileNotFoundError:
            return jsonify({"error": f"No metric data found for key '{k}'", "key": k}), 404

        row = {}
        for field in fields:
            if field not in df.columns:
                return jsonify({
                    "error": f"Field '{field}' not found for key '{k}'",
                    "key": k,
                    "field": field,
                }), 400
            row[field] = float(df.iloc[0][field])
        results[k] = row

    return jsonify({
        "status": "ok",
        "axis": axis,
        "axisLabel": axis_label,
        "props": props,
        "data": results,
        "chart": chart,
    })


@app.post("/api/seed-metric-data")
def seed_metric_data():
    # Lets Chart Studio's "Push to backend" button write its Sample data
    # (the same shape comparison_view() reads) as real per-scenario CSVs -
    # so a chart can be tested against /api/comparison-view immediately,
    # without running the actual computation pipeline. Overwrites any
    # existing metric/<key>.csv for the keys supplied.
    payload = request.get_json(force=True)
    data = payload.get("data")

    if not isinstance(data, dict) or not data:
        return jsonify({"error": "data must be a non-empty object of key -> {field: number}"}), 400

    for key, row in data.items():
        if not CHART_TYPE_NAME_RE.match(key):
            return jsonify({
                "error": f"'{key}' is not a valid scenario key (letters, numbers, underscores, hyphens only)",
            }), 400
        if not isinstance(row, dict) or not row:
            return jsonify({"error": f"value for '{key}' must be a non-empty object of field -> number"}), 400
        for field, value in row.items():
            if not isinstance(value, (int, float)) or isinstance(value, bool):
                return jsonify({
                    "error": f"'{key}.{field}' must be a number, got {type(value).__name__}",
                }), 400

    written = []
    for key, row in data.items():
        csv_text = pd.DataFrame([row]).to_csv(index=False)
        _atomic_write_text(metric_subdir / f"{key}.csv", csv_text)
        written.append(key)

    return jsonify({"status": "ok", "written": written})


@app.get("/api/chart-types")
def list_chart_types():
    manifest = _load_chart_manifest()
    types = [
        {
            "name": rec["name"],
            "description": rec.get("description", ""),
            "createdAt": rec.get("createdAt"),
            # Charts published before the Vega-Lite engine existed have no
            # stored engine - they're implicitly D3.
            "engine": rec.get("engine", "d3"),
        }
        for rec in manifest.values()
    ]
    types.sort(key=lambda t: t["name"])
    return jsonify({"status": "ok", "chartTypes": types})


@app.get("/api/chart-types/<name>")
def get_chart_type(name: str):
    if not CHART_TYPE_NAME_RE.match(name):
        return jsonify({"error": "Invalid chart type name"}), 400

    manifest = _load_chart_manifest()
    record = manifest.get(name)
    if not record:
        return jsonify({"error": f"No chart type named '{name}'"}), 404

    return jsonify({**record, "engine": record.get("engine", "d3")})


@app.post("/api/chart-types")
def publish_chart_type():
    data = request.get_json(force=True)
    name = (data.get("name") or "").strip()
    description = data.get("description", "")
    code = data.get("code", "")
    engine = data.get("engine", "d3")

    if not CHART_TYPE_NAME_RE.match(name):
        return jsonify({
            "error": "Chart type name must be non-empty and contain only letters, numbers, underscores, and hyphens",
        }), 400

    if engine not in ("d3", "vega-lite"):
        return jsonify({"error": "engine must be 'd3' or 'vega-lite'"}), 400

    if engine == "vega-lite":
        try:
            json.loads(code)
        except json.JSONDecodeError as e:
            return jsonify({"error": f"Spec must be valid JSON: {e}"}), 400
    elif not code.strip():
        return jsonify({"error": "code must be non-empty"}), 400

    if not FRONTEND_SRC_DIR.exists():
        return jsonify({
            "error": "Publishing requires the dev stack (docker-compose.dev.yml) - frontend "
                     "source is not mounted in this environment.",
        }), 503

    render_fn_name = "render" + _pascal_case(name)
    component_file = "comparison" + _pascal_case(name) + ".generated.ts"

    manifest = _load_chart_manifest()

    collision = _check_chart_name_collision(name, component_file, manifest)
    if collision:
        return jsonify({"error": collision}), 400

    _atomic_write_text(
        FRONTEND_CHARTS_GENERATED_DIR / component_file,
        _generate_chart_file(render_fn_name, code, engine),
    )

    record = {
        "name": name,
        "description": description,
        "code": code,
        "engine": engine,
        "componentFile": component_file,
        "componentName": render_fn_name,
        "createdAt": datetime.now(timezone.utc).isoformat(),
    }
    manifest[name] = record
    _save_chart_manifest(manifest)
    _regenerate_chart_registry(manifest)

    return jsonify({"status": "ok", **record})

@app.post("/api/infer-filetype")
def infer_filetype():
    payload = request.get_json(silent=True) or {}

    ref_keys = ["ref", "ref_base", "ref_comp"]
    ref = None

    for key in ref_keys:
        if key in payload and payload[key]:
            ref = payload[key]
            break

    if not ref:
        return jsonify({"ok": False, "error": "missing ref"}), 400
    
    result = {
        "ok": True,
        "ref": ref,
        "kind": None,       # "vector" | "raster" | None
        "is_dir": None,     # bool | None
        "file_type": None,        # ".geojson" | ".png" | etc | None
        "path": None,       # optional debug
    }

    vector_path = next(vector_subdir.glob(f"{ref}.*"), None)
    if vector_path is not None:
        return jsonify({
            "ok": True,
            "kind": "vector",
            "is_dir": False,
            "file_type": vector_path.suffix.lower(),
        }), 200
    
    # -------------------------
    # 2) Raster (file OR directory)
    # -------------------------

    # Case 1: direct file match (e.g., A.tif)
    raster_file = next(raster_subdir.glob(f"{ref}.*"), None)
    if raster_file is not None and raster_file.is_file():
        return jsonify({
            "ok": True,
            "kind": "raster",
            "is_dir": False,
            "file_type": raster_file.suffix.lower(),
        }), 200


    # Case 2: directory match (e.g., raster/A/)
    raster_path = raster_subdir / ref
    if raster_path.exists() and raster_path.is_dir():
        any_file = next((p for p in raster_path.iterdir() if p.is_file()), None)
        ext = any_file.suffix.lower() if any_file else None

        return jsonify({
            "ok": True,
            "kind": "raster",
            "is_dir": True,
            "file_type": ext,
        }), 200

    # -------------------------
    # 3) Not found
    # -------------------------
    return jsonify({
        "ok": True,
        "kind": None,
        "is_dir": None,
        "file_type": None,
    }), 200


@app.get("/api/ai/settings")
def ai_settings_get():
    return jsonify(get_public_settings()), 200


@app.post("/api/ai/settings")
def ai_settings_post():
    payload = request.get_json(silent=True) or {}
    settings = update_settings(payload)
    return jsonify(settings), 200


@app.post("/api/ai/provider-models")
def ai_provider_models():
    payload = request.get_json(silent=True) or {}
    try:
        result = list_provider_models(
            payload.get("apiType"), payload.get("baseUrl"), payload.get("apiKey")
        )
    except ChatError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify(result), 200


@app.post("/api/ai/chat")
def ai_chat():
    payload = request.get_json(silent=True) or {}
    messages = payload.get("messages")
    if not isinstance(messages, list) or not messages:
        return jsonify({"error": "messages must be a non-empty list"}), 400

    try:
        reply = run_chat(messages)
    except ChatError as e:
        return jsonify({"error": str(e)}), 400

    return jsonify({"reply": reply}), 200


if __name__ == '__main__':
    # remove old served before starting
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR, ignore_errors=True)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    vector_subdir.mkdir(parents=True, exist_ok=True)
    raster_subdir.mkdir(parents=True, exist_ok=True)
    metric_subdir.mkdir(parents=True, exist_ok=True)

    # Start the worker up-front (or you can let send_code_to_worker lazily do it)
    try:
        start_worker()
    except Exception as e:
        print("[WORKER] Failed to start:", e)

    app.run(host='0.0.0.0', port=9797, debug=True)
