from __future__ import annotations
from copyreg import pickle
import json
import tempfile
import textwrap
from flask import Flask, request, jsonify, send_file, abort
from io import BytesIO
from flask_cors import CORS
import os, re, sys, signal, shutil
from pathlib import Path
from datetime import datetime, timezone
import geopandas as gpd
from flask import send_from_directory, abort
import osmnx as ox
import matplotlib
import pandas as pd
import numpy as np
import cv2
import subprocess
import rasterio
import threading
import json as jsonlib
import uuid

from ai_settings import (
    ChatError,
    get_public_settings,
    list_provider_models,
    run_chat,
    update_settings,
)

worker_proc = None
worker_lock = threading.Lock()
worker_python_exe = None

app = Flask(__name__)
CORS(app)

DATA_DIR = Path("data")
OUT_DIR  = Path("data/served")
CATALOG_DIR = Path("data/catalog")
DATAFLOWS_DIR = Path("data/dataflows")
vector_subdir = Path(OUT_DIR / "vector")
raster_subdir = Path(OUT_DIR / "raster")
metric_subdir = Path(OUT_DIR / "metric")
OUT_DIR.mkdir(parents=True, exist_ok=True)
vector_subdir.mkdir(parents=True, exist_ok=True)
raster_subdir.mkdir(parents=True, exist_ok=True)
metric_subdir.mkdir(parents=True, exist_ok=True)
DATAFLOWS_DIR.mkdir(parents=True, exist_ok=True)

CHART_TYPE_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")
DATAFLOW_ID_RE = re.compile(r"^[a-zA-Z0-9_-]+$")

# Chart Studio "Publish" writes generated chart components directly into
# frontend source (dev only - see docker-compose.dev.yml's frontend_src
# mount on the backend service; production has no such mount, checked at
# publish time). The manifest lives outside OUT_DIR so it survives the
# shutil.rmtree(OUT_DIR) that runs on every backend start/reload below.
FRONTEND_SRC_DIR = Path("/app/frontend_src")
FRONTEND_CHARTS_DIR = FRONTEND_SRC_DIR / "charts"
# Published chart components are generated here; the shared rendering
# engines (genericChartRenderer, customD3Renderer, vegaLite*) live one
# level up in charts/renderers, imported via a relative "../renderers/..."
# path baked into every generated file - see _generate_chart_file().
FRONTEND_CHARTS_GENERATED_DIR = FRONTEND_CHARTS_DIR / "generated"
CHART_MANIFEST_PATH = DATA_DIR / "chart_manifest.json"
CHART_REGISTRY_FILENAME = "customChartRegistry.generated.ts"
# Files a generated chart's name must not collide with (case-insensitively).
# bar/pie/table are ordinary published chart types, not special-cased -
# only genuinely load-bearing hand-written infrastructure is protected here.
RESERVED_CHART_FILES = {
    "renderComparison.tsx", "customD3Renderer.tsx", "genericChartRenderer.tsx",
    "vegaLiteRuntime.ts", "vegaLiteRenderer.tsx", "chartTypes.ts", CHART_REGISTRY_FILENAME,
}


def _pascal_case(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[-_\s]+", name) if p)


# Every published chart's real identifier is minted from its human-readable
# displayName plus this tag - unconditionally, for every chart, not just
# ones that would otherwise collide - so two charts can intentionally share
# a displayName (e.g. a D3 and a Vega-Lite "Grouped bar chart") without ever
# colliding on the manifest key/generated filename that name mints into.
def _engine_tag(engine: str) -> str:
    return "Vega" if engine == "vega-lite" else "D3"


def _atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _load_chart_manifest() -> dict:
    if not CHART_MANIFEST_PATH.exists():
        return {}
    try:
        return json.loads(CHART_MANIFEST_PATH.read_text())
    except json.JSONDecodeError:
        return {}


def _save_chart_manifest(manifest: dict) -> None:
    _atomic_write_text(CHART_MANIFEST_PATH, json.dumps(manifest, indent=2))


def _generate_chart_file(render_fn_name: str, code: str, engine: str) -> str:
    if engine == "vega-lite":
        # code is already validated as parseable JSON by the caller. Embed it
        # as JSON.parse("<escaped text>") rather than a raw JS object literal -
        # a spec with a top-level key literally named "__proto__" behaves
        # differently as a re-parsed JSON string (an own data property, safe)
        # vs. a JS object literal (sets the object's prototype instead). This
        # makes the generated file byte-for-byte equivalent to what the
        # author's editor held, regardless of key names.
        spec_obj = json.loads(code)
        spec_js_string_literal = json.dumps(json.dumps(spec_obj))
        return (
            "// @ts-nocheck\n"
            "// AUTO-GENERATED by Chart Studio (Vega-Lite). Edits here are overwritten on republish.\n"
            "import type { ChartRenderFn } from \"../renderers/genericChartRenderer\";\n"
            "import { renderVegaLiteSpec } from \"../renderers/vegaLiteRuntime\";\n\n"
            f"const SPEC = JSON.parse({spec_js_string_literal});\n\n"
            f"export const {render_fn_name}: ChartRenderFn = (container, data, params, d3, containerWidth) => {{\n"
            "  return renderVegaLiteSpec(container, SPEC, data, containerWidth);\n"
            "};\n"
        )

    indented_code = textwrap.indent(code.rstrip(), "  ")
    return (
        # @ts-nocheck: pasted D3/JS is arbitrary author code, not written
        # against this project's strict tsconfig (noImplicitAny on untyped
        # D3 callback params, noUnusedParameters when a chart doesn't need
        # every one of container/data/params/d3, etc.) - a genuine syntax
        # error still fails to parse and is not suppressed by this. The
        # ChartRenderFn annotation below is inert under @ts-nocheck (nothing
        # is actually checked against it) - it's kept anyway so every
        # generated chart file reads the same way, regardless of name.
        "// @ts-nocheck\n"
        "// AUTO-GENERATED by Chart Studio. Edits here are overwritten on republish.\n"
        "import type { ChartRenderFn } from \"../renderers/genericChartRenderer\";\n\n"
        f"export const {render_fn_name}: ChartRenderFn = (container, data, params, d3, containerWidth) => {{\n"
        "  container.innerHTML = \"\";\n"
        f"{indented_code}\n"
        "};\n"
    )


def _regenerate_chart_registry(manifest: dict) -> None:
    imports = [
        f'import {{ {rec["componentName"]} }} from "./{rec["componentFile"][:-3]}";'
        for rec in manifest.values()
    ]
    entries = [f"  {json.dumps(name)}: {rec['componentName']}," for name, rec in manifest.items()]
    content = (
        "// AUTO-GENERATED by Chart Studio publish. Do not edit by hand - regenerated\n"
        "// in full on every publish.\n"
        'import type { ChartRenderFn } from "../renderers/genericChartRenderer";\n'
        + ("\n" + "\n".join(imports) + "\n" if imports else "\n")
        + "\nexport const customChartRenderers: Record<string, ChartRenderFn> = {\n"
        + ("\n".join(entries) + "\n" if entries else "")
        + "};\n"
    )
    _atomic_write_text(FRONTEND_CHARTS_GENERATED_DIR / CHART_REGISTRY_FILENAME, content)


def _check_chart_name_collision(name: str, component_file: str, manifest: dict) -> str | None:
    cf_lower = component_file.lower()
    if cf_lower in {f.lower() for f in RESERVED_CHART_FILES}:
        return f"'{name}' would generate '{component_file}', which collides with an existing built-in file"
    for other_name, rec in manifest.items():
        if other_name == name:
            continue  # republishing the same chart overwrites itself - allowed
        if rec["componentFile"].lower() == cf_lower:
            return f"'{name}' collides with existing chart type '{other_name}' (both generate {component_file})"
    return None

def start_worker():
    global worker_proc, worker_python_exe

    if worker_proc is not None and worker_proc.poll() is None:
        # already running
        return

    project_dir = Path(__file__).parent
    python_exe = Path(sys.executable)

    if not python_exe.exists():
        python_exe = project_dir / "envs" / ("python.exe" if os.name == "nt" else "bin/python")

    if not python_exe.exists():
        raise RuntimeError(f"Python interpreter not found at: {python_exe}")

    worker_python_exe = python_exe

    worker_proc = subprocess.Popen(
        [str(python_exe), "-u", "python_worker.py"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        cwd=str(project_dir),
        env={**os.environ, "PYTHONPATH": str(project_dir) + os.pathsep + os.environ.get("PYTHONPATH", "")},
        bufsize=1,  # line-buffered
    )

    print("[WORKER] Started python_worker process PID:", worker_proc.pid)

def send_code_to_worker(code: str) -> dict:
    """
    Sends code to the persistent worker and returns a dict:
    { "ok": bool, "stdout": str, "stderr": str }
    """
    global worker_proc

    if worker_proc is None or worker_proc.poll() is not None:
        start_worker()

    with worker_lock:
        req = {"code": code}
        line = jsonlib.dumps(req) + "\n"

        assert worker_proc.stdin is not None
        worker_proc.stdin.write(line)
        worker_proc.stdin.flush()

        assert worker_proc.stdout is not None
        resp_line = worker_proc.stdout.readline()
        if not resp_line:
            raise RuntimeError("Worker process terminated unexpectedly")

    resp = jsonlib.loads(resp_line)
    return resp

# Remove cached outputs on exit
def cleanup_served():
    try:
        out_resolved = OUT_DIR.resolve()
        data_resolved = DATA_DIR.resolve()
        if data_resolved in out_resolved.parents and out_resolved.name == "served":
            if OUT_DIR.exists():
                shutil.rmtree(OUT_DIR, ignore_errors=True)
                print(f"[CLEANUP] Removed {OUT_DIR}")
        else:
            print(f"[CLEANUP] Refusing to remove unexpected path: {OUT_DIR}")
    except Exception as e:
        app.logger.error(f"[CLEANUP] Failed: {e}")

def register_cleanup_handlers():
    import atexit
    atexit.register(cleanup_served)

    def _handler(sig, frame):
        cleanup_served()
        sys.exit(0)

    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            signal.signal(sig, _handler)
        except Exception:
            pass

if os.environ.get("WERKZEUG_RUN_MAIN") == "true" or not app.debug:
    register_cleanup_handlers()

def resolve_feather_path(datafile: str, tag: str) -> Path:
    return CATALOG_DIR / "osm" / datafile / f"{tag}.feather"

def load_roi_mask(roi: dict) -> tuple[str, object]:
    rtype = roi.get("type")
    val = roi.get("value")
    if rtype == "bbox":
        xmin, ymin, xmax, ymax = map(float, val)
        return "bbox", (xmin, ymin, xmax, ymax)
    
    elif rtype == "geojson":
        roi_path = Path(val)
        roi_path = DATA_DIR / str(val)

        # Try this later in notebook and then add.. 

        # mask_gdf = gpd.read_file(roi_path)
        # mask = mask_gdf.union_all()
        # return "mask", gpd.GeoDataFrame(geometry=[mask], crs=mask_gdf.crs)

def crop_gdf(gdf: gpd.GeoDataFrame, roi_dict: dict) -> gpd.GeoDataFrame:
    roi_kind, roi = load_roi_mask(roi_dict)

    if roi_kind == "bbox":
        xmin, ymin, xmax, ymax = roi
        return gdf.cx[xmin:xmax, ymin:ymax]
    else:
        mask_gdf = roi  
        if mask_gdf.crs is None:
            mask_gdf = mask_gdf.set_crs(4326, allow_override=True)

        return gpd.clip(gdf, mask_gdf)
    
def select_features(gdf: gpd.GeoDataFrame, features: list[str]) -> gpd.GeoDataFrame:
    existing = [f for f in features if f in gdf.columns]
    cols = existing + (["geometry"] if "geometry" in gdf.columns else [])
    
    return gdf[cols]

def _list_png_tiles(folder: Path) -> list[str]:
    return [
        f.name
        for f in folder.iterdir()
        if f.is_file() and f.suffix.lower() == ".png"
    ]


@app.get("/api/list-rasters/<path:Id>")
def list_rasters(Id: str):
    """
    Return a JSON list of PNG raster tiles inside a raster ref's folder -
    normally data/catalog/<Id>/ or this dataflow's
    data/dataflows/<dataflow_id>_computed/<Id>/, falling back to
    data/served/raster/<Id>/ for rasters written directly by model scripts
    (flood/shadow/routing - see _resolve_data_source), which have no
    catalog/computed identity of their own.
    """
    dataflow_id = request.args.get("dataflow_id")

    resolved = _resolve_data_source(Id, dataflow_id)
    if resolved is not None:
        base_dir, rel_ref = resolved
        folder = _safe_data_dir(base_dir, rel_ref)
        if folder is not None and folder.is_dir():
            return jsonify(_list_png_tiles(folder)), 200

    folder = raster_subdir / Id
    try:
        folder.resolve().relative_to(raster_subdir.resolve())
    except Exception:
        return jsonify({"error": "Invalid raster folder"}), 403

    if not folder.exists() or not folder.is_dir():
        return jsonify([]), 200   # return empty list

    return jsonify(_list_png_tiles(folder)), 200

@app.get("/generated/raster/<path:filename>")
def serve_raster(filename: str):
    allowed_exts = {"png", "tif", "tiff"}

    try:
      ext = filename.rsplit(".", 1)[1].lower()
    except IndexError:
      abort(404)

    if ext not in allowed_exts:
        abort(404)

    mimetype = "image/png" if ext == "png" else "image/tiff"
    ref = filename[: -(len(ext) + 1)]
    dataflow_id = request.args.get("dataflow_id")

    resolved = _resolve_data_source(ref, dataflow_id)
    if resolved is not None:
        base_dir, rel_ref = resolved
        candidate = _safe_data_path(base_dir, rel_ref, ext)
        if candidate is not None and candidate.is_file():
            return send_from_directory(
                candidate.parent, candidate.name, mimetype=mimetype, conditional=True,
            )

    # Fall back to data/served/raster - where model scripts (flood/shadow/
    # routing) write their raster outputs directly, with no catalog/computed
    # identity of their own (see _resolve_data_source).
    full_path = raster_subdir / filename
    try:
        full_path.resolve().relative_to(raster_subdir.resolve())
    except Exception:
        abort(403)  # Forbidden

    if not full_path.is_file():
        abort(404)

    return send_from_directory(
        full_path.parent,
        full_path.name,
        mimetype=mimetype,
        conditional=True,
    )

@app.get("/generated/vector/<path:filename>")
def serve_vector(filename: str):
    if not filename.lower().endswith(".geojson"):
        abort(404)

    ref = filename[: -len(".geojson")]
    dataflow_id = request.args.get("dataflow_id")

    resolved = _resolve_data_source(ref, dataflow_id)
    if resolved is not None:
        base_dir, rel_ref = resolved
        candidate = _safe_data_path(base_dir, rel_ref, "geojson")
        if candidate is not None and candidate.is_file():
            return send_from_directory(
                candidate.parent,
                candidate.name,
                mimetype="application/geo+json",
                conditional=True,
            )

    # Fall back to data/served/vector - where model scripts (e.g. weather
    # routing) write vector outputs directly, with no catalog/computed
    # identity of their own (see _resolve_data_source).
    full_path = vector_subdir / filename
    try:
        full_path.resolve().relative_to(vector_subdir.resolve())
    except Exception:
        abort(403)

    if not full_path.is_file():
        abort(404)

    return send_from_directory(
        full_path.parent,
        full_path.name,
        mimetype="application/geo+json",
        conditional=True,
    )

_CATALOG_FORMAT_LABELS = {
    ".feather": "Feather",
    ".parquet": "Parquet",
    ".csv": "CSV",
    ".geojson": "GeoJSON",
    ".json": "JSON",
    ".tif": "GeoTIFF",
    ".tiff": "GeoTIFF",
    ".pbf": "OSM PBF",
    ".pkl": "Pickle",
    ".gz": "Gzip",
}
# Extensions checked as a whole filename suffix (not just the last dotted
# part) so a name like "roads.pkl.gz" gets one label instead of just "Gzip".
_CATALOG_COMPOUND_FORMATS = {
    ".pkl.gz": "Pickle (gzip)",
}


def _catalog_format_label(path: Path) -> str:
    lower = path.name.lower()
    for suffix, label in _CATALOG_COMPOUND_FORMATS.items():
        if lower.endswith(suffix):
            return label
    return _CATALOG_FORMAT_LABELS.get(path.suffix.lower(), path.suffix.lstrip(".").upper() or "File")


def _catalog_display_name(path: Path) -> str:
    # Keep the on-disk name as-is (underscores included) rather than
    # prettifying it - it's still a real filename, not a free-text title.
    lower = path.name.lower()
    for suffix in _CATALOG_COMPOUND_FORMATS:
        if lower.endswith(suffix):
            return path.name[: -len(suffix)]
    return path.stem


def _catalog_human_size(num_bytes: int) -> str:
    size = float(num_bytes)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


@app.get("/api/data-catalog")
def list_data_catalog():
    """Lists every file under data/catalog/ for the frontend's Data Catalog
    sidebar. Each file becomes one dataset entry, grouped by its top-level
    subfolder under the catalog root (e.g. "osm", "quad_city_flooding")."""
    if not CATALOG_DIR.exists():
        return jsonify({"status": "ok", "datasets": []})

    datasets = []
    for path in sorted(CATALOG_DIR.rglob("*")):
        if not path.is_file() or path.name.startswith("."):
            continue

        rel = path.relative_to(CATALOG_DIR)
        stat = path.stat()

        datasets.append({
            "id": rel.as_posix(),
            "name": _catalog_display_name(path),
            "group": rel.parts[0] if len(rel.parts) > 1 else "general",
            "format": _catalog_format_label(path),
            "sizeBytes": stat.st_size,
            "size": _catalog_human_size(stat.st_size),
            "modifiedAt": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
        })

    return jsonify({"status": "ok", "datasets": datasets})


@app.post('/api/extract-data-layer')
def extract_data_layer():
    payload = request.get_json(silent=True) or {}
    pl = payload
    problems = []
    computed = []

    id = pl.get("id")
    src = pl.get("source")
    dtype = pl.get("dtype")
    dataflow_id = pl.get("dataflow_id")

    # datafile = pl.get("datafile")
    roi = pl.get("roi") or {}
    roi_datafile = pl.get("roi").get("datafile")

    if not dataflow_id:
        return jsonify({"status": "error", "error": "dataflow_id is required"}), 400

    dataflow_path = _dataflow_path(str(dataflow_id))
    if dataflow_path is None or not dataflow_path.exists():
        return jsonify({"status": "error", "error": f"No dataflow with id '{dataflow_id}'"}), 404

    try:
        dataflow_record = json.loads(dataflow_path.read_text())
    except json.JSONDecodeError:
        dataflow_record = {}

    # A feature can only be fetched if its catalog file has actually been
    # added to this dataflow's project - "added to project" is just this
    # permission check, not a copy of the file (see projectDatasets on the
    # saved dataflow record).
    project_dataset_ids = {
        d.get("id")
        for d in (dataflow_record.get("projectDatasets") or [])
        if isinstance(d, dict)
    }

    if(src == "osm"):
        for f in (pl.get("osm_features") or []):
            feature = f.get("feature")
            attributes = f.get("attributes") or []
            catalog_id = f"osm/{roi_datafile}/{feature}.feather"

            if catalog_id not in project_dataset_ids:
                problems.append({
                    "data_layer_id": id,
                    "feature": feature,
                    "error": (
                        f"'{feature}' ({catalog_id}) is not available in this project - "
                        "add it from the Data Catalog first."
                    ),
                })
                continue

            try:
                src_path = resolve_feather_path(str(roi_datafile), str(feature))
                if not src_path.is_file():
                    raise FileNotFoundError(f"Missing source: {src_path}")
                print(f"    Loading data from: {src_path}")
                gdf = gpd.read_feather(src_path)

                gdf_cut = crop_gdf(gdf, roi)
                gdf_out = select_features(gdf_cut, attributes)

                out_name = f"{id}_{feature}.geojson"
                out_path = vector_subdir / out_name

                gdf_out.to_file(out_path, driver="GeoJSON")

                # Durable copy - out_path itself lives under OUT_DIR, which
                # gets wiped on every backend restart (see __main__ below).
                computed_dir = _dataflow_computed_dir(str(dataflow_id))
                computed_dir.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(out_path, computed_dir / out_name)

                stat = out_path.stat()
                computed.append({
                    "id": f"computed/{out_name}",
                    "name": f"{id}_{feature}",
                    "group": "computed",
                    "format": "GeoJSON",
                    "sizeBytes": stat.st_size,
                    "size": _catalog_human_size(stat.st_size),
                    "modifiedAt": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
                })

            except Exception as e:
                error_msg = f"[ERROR] Layer {id}:{feature} → {type(e).__name__}: {e}"
                print(error_msg)

                problems.append({
                    "data_layer_id": id,
                    "feature": feature,
                    "error": str(e)
                })

        return jsonify({
            "status": "success" if not problems else "partial",
            "problems": problems,
            "computed": computed,
        }), 200 if not problems else 207
    else:
        return jsonify({"status": "error", "error": f"Unsupported source: {src}"}), 400


@app.route("/api/update-data-layer", methods=["POST"])
def update_data_layer():
    data = request.get_json()
    ref = data["ref"]
    dataflow_id = data.get("dataflow_id")
    geojson = data["geojson"]

    # A "computed/" ref is this dataflow's own mutable output - edits persist
    # there durably (data/dataflows/{dataflow_id}_computed/), the same place
    # the view/interaction ref resolution looks it up from (see
    # _resolve_data_source). Anything else falls back to data/served/vector,
    # matching the pre-existing behavior for refs that come from a model
    # script's direct output (flood/shadow/routing) rather than the catalog
    # or a computed dataset - the catalog itself is never written to here.
    resolved = _resolve_data_source(ref, dataflow_id) if ref.startswith("computed/") else None

    if resolved is not None:
        base_dir, rel_ref = resolved
        filepath = _safe_data_path(base_dir, rel_ref, "geojson")
        if filepath is None:
            return jsonify({"status": "error", "error": "invalid ref"}), 400
        _atomic_write_text(filepath, json.dumps(geojson))
        return jsonify({"status": "success"}), 200

    filename = f"vector/{ref}.geojson"
    filepath = OUT_DIR / filename

    with open(filepath, "w") as f:
        json.dump(geojson, f)

    return jsonify({"status": "success"}), 200

@app.post("/api/run-python")
def run_python():
    payload = request.get_json() or {}
    code = payload.get("code", "")

    print("Received code to run:\n", code)

    try:
        resp = send_code_to_worker(code)
        # resp: {"ok": bool, "stdout": "...", "stderr": "..."}

        return jsonify({
            "stdout": resp.get("stdout", ""),
            "stderr": resp.get("stderr", ""),
            "returncode": 0 if resp.get("ok") else 1,
        }), 200

    except Exception as e:
        # If something goes really wrong (worker dead, etc.)
        return jsonify({
            "stdout": "",
            "stderr": f"Worker error: {e}",
            "returncode": -1,
        }), 200
    
COLORMAPS = {
    "viridis": matplotlib.colormaps.get_cmap("viridis"),
    "reds": matplotlib.colormaps.get_cmap("Reds"),
    "greens": matplotlib.colormaps.get_cmap("Greens"),
    "blues": matplotlib.colormaps.get_cmap("Blues"),
    "grays":   matplotlib.colormaps.get_cmap("Greys")
}

def _resolve_raster_dir(ref: str, dataflow_id: str | None) -> Path | None:
    """Resolves a raster tile-folder ref to its actual directory: tries the
    catalog / this dataflow's computed dir first (see _resolve_data_source),
    then falls back to data/served/raster/<ref> for folders written
    directly by model scripts (flood/shadow), which have no catalog/computed
    identity of their own."""
    resolved = _resolve_data_source(ref, dataflow_id)
    if resolved is not None:
        base_dir, rel_ref = resolved
        folder = _safe_data_dir(base_dir, rel_ref)
        if folder is not None and folder.is_dir():
            return folder

    folder = raster_subdir / ref
    try:
        folder.resolve().relative_to(raster_subdir.resolve())
    except Exception:
        return None
    return folder if folder.is_dir() else None


def _resolve_raster_file(ref: str, ext: str, dataflow_id: str | None) -> Path | None:
    """Single-file counterpart of _resolve_raster_dir (e.g. a .tif)."""
    resolved = _resolve_data_source(ref, dataflow_id)
    if resolved is not None:
        base_dir, rel_ref = resolved
        candidate = _safe_data_path(base_dir, rel_ref, ext)
        if candidate is not None and candidate.is_file():
            return candidate

    candidate = raster_subdir / f"{ref}.{ext}"
    try:
        candidate.resolve().relative_to(raster_subdir.resolve())
    except Exception:
        return None
    return candidate if candidate.is_file() else None


@app.get("/generated/raster/<ref>/<name>")
def get_colormapped_tile(ref, name):
    dataflow_id = request.args.get("dataflow_id")
    folder = _resolve_raster_dir(ref, dataflow_id)
    if folder is None:
        abort(404)

    path = folder / name
    try:
        path.resolve().relative_to(folder.resolve())
    except Exception:
        abort(403)

    cmap_name = (request.args.get("cmap") or "").lower()
    cmap = COLORMAPS.get(cmap_name)

    # If no/unknown colormap → return original PNG
    if cmap is None:
        return send_file(path, mimetype="image/png")

    # Read image (gray / BGR / BGRA)
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        abort(404)

    # ---- extract grayscale 0–255 ----
    if img.ndim == 2:
        gray = img.astype(np.float32)
        alpha = None
    elif img.shape[2] == 4:
        gray = img[:, :, 0].astype(np.float32)
        alpha = img[:, :, 3]
    else:
        gray = img[:, :, 0].astype(np.float32)
        alpha = None

    # ---- normalize FIXED 0–255 ----
    t = np.clip(gray / 255.0, 0.0, 1.0)

    # ---- apply matplotlib colormap ----
    rgba = (cmap(t) * 255).astype(np.uint8)  # H x W x 4

    # ---- preserve alpha if present ----
    if alpha is not None:
        rgba[:, :, 3] = alpha

    rgba = rgba[..., [2, 1, 0, 3]]  # RGBA -> BGRA for OpenCV

    ok, buf = cv2.imencode(".png", rgba)
    if not ok:
        abort(500)

    return send_file(BytesIO(buf.tobytes()), mimetype="image/png")
    
def _diff_ref_name(ref_base: str, ref_comp: str) -> str:
    # ref_base/ref_comp may contain "/" ("folder/file" or "computed/...") -
    # flatten to a flat data/served/raster cache key for the synthesized
    # diff output, which has no catalog/computed identity of its own.
    return f"{ref_base.replace('/', '__')}_minus_{ref_comp.replace('/', '__')}"


def diff_dirs(dir1: Path, dir2: Path, out_name: str) -> Path:
    output_path = Path(raster_subdir, out_name)

    if output_path.exists():
        shutil.rmtree(output_path)
    output_path.mkdir(parents=True, exist_ok=True)

    for png1 in sorted(dir1.glob("*.png")):
        png2 = dir2 / png1.name
        if not png2.exists():
            print(f"Skipping {png1.name}: not found in {dir2}")
            continue

        # Read as grayscale (single channel 0..255)
        gray1 = cv2.imread(str(png1), cv2.IMREAD_GRAYSCALE)
        gray2 = cv2.imread(str(png2), cv2.IMREAD_GRAYSCALE)

        if gray1 is None or gray2 is None:
            print(f"Skipping {png1.name}: failed to read one of the images")
            continue

        # absolute difference in 0..255 (uint8)
        diff_u8 = cv2.absdiff(gray2, gray1)

        # Save as grayscale PNG (no colormap baked in)
        cv2.imwrite(str(output_path / png1.name), diff_u8)

    return output_path

@app.route("/api/diff-png", methods=["POST"])
def api_diff_png():
    data = request.get_json(force=True)
    ref_base = data.get("ref_base") or data.get("dir1")
    ref_comp = data.get("ref_comp") or data.get("dir2")
    dataflow_id = data.get("dataflow_id")
    # colormap = data.get("colormap", "Reds")

    if not ref_base or not ref_comp:
        return jsonify({"error": "ref_base and ref_comp are required"}), 400

    dir1 = _resolve_raster_dir(ref_base, dataflow_id)
    dir2 = _resolve_raster_dir(ref_comp, dataflow_id)
    if dir1 is None or dir2 is None:
        return jsonify({"error": "ref_base/ref_comp raster folder not found"}), 404

    out_name = _diff_ref_name(ref_base, ref_comp)
    out_dir = diff_dirs(dir1, dir2, out_name)
    return jsonify({
        "status": "ok",
        "output_dir": str(out_dir),
        "ref": out_name,
    })

def diff_tif_files(tif1_path: Path, tif2_path: Path, out_name: str) -> Path:
    out_path = Path(raster_subdir, f"{out_name}.tif")

    with rasterio.open(tif1_path) as r1, rasterio.open(tif2_path) as r2:
        arr1 = r1.read(1).astype("float32")
        arr2 = r2.read(1).astype("float32")

        # Difference: scenario2 - scenario1
        diff = np.abs(arr2 - arr1)

        profile = r1.profile
        profile.update(
            dtype="float32",
            count=1,
        )

        with rasterio.open(out_path, "w", **profile) as dst:
            dst.write(diff, 1)

    return out_path

@app.route("/api/diff-tif", methods=["POST"])
def api_diff_tif():
    data = request.get_json(force=True)
    ref_base = data.get("ref_base") or data.get("tif1")
    ref_comp = data.get("ref_comp") or data.get("tif2")
    dataflow_id = data.get("dataflow_id")

    if not ref_base or not ref_comp:
        return jsonify({"error": "ref_base and ref_comp are required"}), 400

    tif1_path = _resolve_raster_file(ref_base, "tif", dataflow_id)
    tif2_path = _resolve_raster_file(ref_comp, "tif", dataflow_id)
    if tif1_path is None or tif2_path is None:
        return jsonify({"error": "ref_base/ref_comp raster file not found"}), 404

    out_name = _diff_ref_name(ref_base, ref_comp)
    out_path = diff_tif_files(tif1_path, tif2_path, out_name)

    return jsonify({
        "status": "ok",
        "output_tif": str(out_path),
        "ref": out_name,
    })

def _as_field_list(value):
    """comparison grammar: x*/y* - a bare string is shorthand for a 1-item set."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


@app.post("/api/comparison-view")
def comparison_view():
    data = request.get_json(force=True)

    print("Received comparison view request:", data)
    key = data.get("key", [])
    x_fields = _as_field_list(data.get("x"))
    y_fields = _as_field_list(data.get("y"))
    chart = data.get("chart", "")
    props = data.get("props", {})

    if not key:
        return jsonify({"error": "key must be non-empty"}), 400

    fields = x_fields + y_fields
    if not fields:
        return jsonify({"error": "At least one field must be declared via x or y"}), 400

    axis = "x" if x_fields else "y"
    axis_label = fields[0]

    results = {}  # per scenario key: only the fields declared via x/y
    for k in key:
        csv_path = metric_subdir / f"{k}.csv"
        try:
            df = pd.read_csv(csv_path)
        except FileNotFoundError:
            return jsonify({"error": f"No metric data found for key '{k}'", "key": k}), 404

        row = {}
        for field in fields:
            if field not in df.columns:
                return jsonify({
                    "error": f"Field '{field}' not found for key '{k}'",
                    "key": k,
                    "field": field,
                }), 400
            row[field] = float(df.iloc[0][field])
        results[k] = row

    return jsonify({
        "status": "ok",
        "axis": axis,
        "axisLabel": axis_label,
        "props": props,
        "data": results,
        "chart": chart,
    })


@app.post("/api/seed-metric-data")
def seed_metric_data():
    # Lets Chart Studio's "Push to backend" button write its Sample data
    # (the same shape comparison_view() reads) as real per-scenario CSVs -
    # so a chart can be tested against /api/comparison-view immediately,
    # without running the actual computation pipeline. Overwrites any
    # existing metric/<key>.csv for the keys supplied.
    payload = request.get_json(force=True)
    data = payload.get("data")

    if not isinstance(data, dict) or not data:
        return jsonify({"error": "data must be a non-empty object of key -> {field: number}"}), 400

    for key, row in data.items():
        if not CHART_TYPE_NAME_RE.match(key):
            return jsonify({
                "error": f"'{key}' is not a valid scenario key (letters, numbers, underscores, hyphens only)",
            }), 400
        if not isinstance(row, dict) or not row:
            return jsonify({"error": f"value for '{key}' must be a non-empty object of field -> number"}), 400
        for field, value in row.items():
            if not isinstance(value, (int, float)) or isinstance(value, bool):
                return jsonify({
                    "error": f"'{key}.{field}' must be a number, got {type(value).__name__}",
                }), 400

    written = []
    for key, row in data.items():
        csv_text = pd.DataFrame([row]).to_csv(index=False)
        _atomic_write_text(metric_subdir / f"{key}.csv", csv_text)
        written.append(key)

    return jsonify({"status": "ok", "written": written})


@app.get("/api/chart-types")
def list_chart_types():
    manifest = _load_chart_manifest()
    types = [
        {
            "name": rec["name"],
            # Charts published before displayName existed fall back to their
            # raw technical name - still legible, just not as pretty.
            "displayName": rec.get("displayName", rec["name"]),
            "description": rec.get("description", ""),
            "createdAt": rec.get("createdAt"),
            # Charts published before the Vega-Lite engine existed have no
            # stored engine - they're implicitly D3.
            "engine": rec.get("engine", "d3"),
        }
        for rec in manifest.values()
    ]
    types.sort(key=lambda t: t["name"])
    return jsonify({"status": "ok", "chartTypes": types})


@app.get("/api/chart-types/<name>")
def get_chart_type(name: str):
    if not CHART_TYPE_NAME_RE.match(name):
        return jsonify({"error": "Invalid chart type name"}), 400

    manifest = _load_chart_manifest()
    record = manifest.get(name)
    if not record:
        return jsonify({"error": f"No chart type named '{name}'"}), 404

    return jsonify({
        **record,
        "displayName": record.get("displayName", record["name"]),
        "engine": record.get("engine", "d3"),
    })


@app.post("/api/chart-types")
def publish_chart_type():
    data = request.get_json(force=True)
    # Set only when re-publishing a chart Chart Studio already loaded (via
    # "Load existing chart" or "Edit in Chart Studio") - overwrites that
    # exact chart in place, under its existing real identifier, regardless
    # of what displayName now says. Omitted for a brand-new chart, whose
    # real identifier doesn't exist yet and is minted below.
    existing_name = (data.get("name") or "").strip()
    display_name = (data.get("displayName") or "").strip()
    description = data.get("description", "")
    code = data.get("code", "")
    engine = data.get("engine", "d3")
    # The "Example usage"/"Sample data" JSON Chart Studio's Preview uses -
    # persisted so republishing doesn't lose an author's edits to them, and
    # so loading this chart back into Studio (or eventually Chart Gallery)
    # can show the same worked example again instead of a guessed one.
    example_usage = data.get("exampleUsage")
    sample_data = data.get("sampleData")

    if not display_name:
        return jsonify({"error": "Chart name must be non-empty"}), 400

    if engine not in ("d3", "vega-lite"):
        return jsonify({"error": "engine must be 'd3' or 'vega-lite'"}), 400

    if engine == "vega-lite":
        try:
            json.loads(code)
        except json.JSONDecodeError as e:
            return jsonify({"error": f"Spec must be valid JSON: {e}"}), 400
    elif not code.strip():
        return jsonify({"error": "code must be non-empty"}), 400

    if not FRONTEND_SRC_DIR.exists():
        return jsonify({
            "error": "Publishing requires the dev stack (docker-compose.dev.yml) - frontend "
                     "source is not mounted in this environment.",
        }), 503

    manifest = _load_chart_manifest()

    if existing_name:
        if not CHART_TYPE_NAME_RE.match(existing_name) or existing_name not in manifest:
            return jsonify({"error": f"No existing chart type named '{existing_name}'"}), 404
        name = existing_name
    else:
        # Minted from displayName + engine, invisible to the author (who
        # only ever sees/edits displayName) - see _engine_tag().
        name = _pascal_case(display_name) + _engine_tag(engine)

    render_fn_name = "render" + _pascal_case(name)
    component_file = "comparison" + _pascal_case(name) + ".generated.ts"

    collision = _check_chart_name_collision(name, component_file, manifest)
    if collision:
        return jsonify({"error": collision}), 400

    _atomic_write_text(
        FRONTEND_CHARTS_GENERATED_DIR / component_file,
        _generate_chart_file(render_fn_name, code, engine),
    )

    record = {
        "name": name,
        "displayName": display_name,
        "description": description,
        "code": code,
        "engine": engine,
        "exampleUsage": example_usage,
        "sampleData": sample_data,
        "componentFile": component_file,
        "componentName": render_fn_name,
        "createdAt": datetime.now(timezone.utc).isoformat(),
    }
    manifest[name] = record
    _save_chart_manifest(manifest)
    _regenerate_chart_registry(manifest)

    return jsonify({"status": "ok", **record})


def _dataflow_path(dataflow_id: str) -> Path | None:
    if not DATAFLOW_ID_RE.match(dataflow_id):
        return None
    return DATAFLOWS_DIR / f"{dataflow_id}.json"


# Durable home for a dataflow's computed outputs (e.g. A_buildings.geojson)
# - unlike data/served (OUT_DIR), which is wiped on every backend
# start/reload, this lives alongside the dataflow's own record and survives
# a restart. See _restore_computed_outputs, called at startup, which copies
# these back into OUT_DIR so a computed dataset's file is actually there
# again, not just its listing in the dataflow's projectDatasets.
def _dataflow_computed_dir(dataflow_id: str) -> Path:
    return DATAFLOWS_DIR / f"{dataflow_id}_computed"


# A view/interaction "ref" (e.g. "osm/quad_city_flooding/buildings" or
# "computed/A_buildings") names a dataset the same way /api/data-catalog and
# /api/extract-data-layer's "id" fields already do - no leading/trailing
# slash, no ".." segments (path traversal guard for the resolver below).
REF_RE = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_\-./]*$")


def _resolve_data_source(ref: str, dataflow_id: str | None) -> tuple[Path, str] | None:
    """Maps a "ref" to the directory it should be read from (or written
    into): a "computed/" prefix scopes it to the current dataflow's own
    computed outputs (data/dataflows/{dataflow_id}_computed/, requires a
    valid dataflow_id); anything else is a path into the shared, read-only
    data catalog (data/catalog/). Returns (base_dir, rel_ref) with rel_ref
    stripped of the "computed/" prefix and still extension-less, or None if
    ref is malformed or a computed ref has no usable dataflow_id."""
    if not ref or not REF_RE.match(ref) or ".." in ref.split("/"):
        return None

    if ref.startswith("computed/"):
        if not dataflow_id or not DATAFLOW_ID_RE.match(dataflow_id):
            return None
        rel_ref = ref[len("computed/"):]
        if not rel_ref:
            return None
        return _dataflow_computed_dir(dataflow_id), rel_ref

    return CATALOG_DIR, ref


def _safe_data_path(base_dir: Path, rel_ref: str, ext: str) -> Path | None:
    """Joins rel_ref + ext onto base_dir, refusing to resolve outside it."""
    full_path = (base_dir / f"{rel_ref}.{ext}").resolve()
    try:
        full_path.relative_to(base_dir.resolve())
    except ValueError:
        return None
    return full_path


def _safe_data_dir(base_dir: Path, rel_ref: str) -> Path | None:
    """Like _safe_data_path but for a ref that names a folder (a raster
    tile set) rather than a single file."""
    full_dir = (base_dir / rel_ref).resolve()
    try:
        full_dir.relative_to(base_dir.resolve())
    except ValueError:
        return None
    return full_dir


def _restore_computed_outputs() -> None:
    for record_path in DATAFLOWS_DIR.glob("*.json"):
        try:
            record = json.loads(record_path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        dataflow_id = record.get("id")
        if not isinstance(dataflow_id, str) or not DATAFLOW_ID_RE.match(dataflow_id):
            continue
        computed_dir = _dataflow_computed_dir(dataflow_id)
        if not computed_dir.is_dir():
            continue
        for f in computed_dir.glob("*.geojson"):
            try:
                shutil.copyfile(f, vector_subdir / f.name)
            except OSError as e:
                print(f"[startup] Failed to restore computed output {f}: {e}")


def _dataflow_summary(record: dict) -> dict:
    nodes = [n for n in (record.get("nodes") or []) if isinstance(n, dict)]
    edges = [e for e in (record.get("edges") or []) if isinstance(e, dict)]
    return {
        "id": record["id"],
        "name": record.get("name") or "Untitled dataflow",
        "createdAt": record.get("createdAt"),
        "updatedAt": record.get("updatedAt"),
        "nodeCount": len(nodes),
        # Just enough per node/edge to draw a canvas-layout thumbnail on the
        # Dataflows home page (see ProjectsHomePage.tsx) without shipping
        # each node's full (potentially large) `data` payload in the list
        # response.
        "nodesPreview": [
            {
                "id": n.get("id"),
                "type": n.get("type"),
                "position": n.get("position") or {"x": 0, "y": 0},
                "width": n.get("width"),
                "height": n.get("height"),
            }
            for n in nodes
        ],
        "edgesPreview": [
            {"source": e.get("source"), "target": e.get("target")} for e in edges
        ],
    }


@app.get("/api/dataflows")
def list_dataflows():
    summaries = []
    for path in DATAFLOWS_DIR.glob("*.json"):
        try:
            record = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        summaries.append(_dataflow_summary(record))

    summaries.sort(key=lambda s: s.get("updatedAt") or "", reverse=True)
    return jsonify({"status": "ok", "dataflows": summaries})


@app.post("/api/dataflows")
def create_dataflow():
    payload = request.get_json(silent=True) or {}
    name = (payload.get("name") or "").strip() or "Untitled dataflow"

    dataflow_id = uuid.uuid4().hex
    now = datetime.now(timezone.utc).isoformat()
    record = {
        "id": dataflow_id,
        "name": name,
        "nodes": [],
        "edges": [],
        "projectDatasets": [],
        "createdAt": now,
        "updatedAt": now,
    }
    _atomic_write_text(DATAFLOWS_DIR / f"{dataflow_id}.json", json.dumps(record))
    return jsonify({"status": "ok", **record})


@app.get("/api/dataflows/<dataflow_id>")
def get_dataflow(dataflow_id: str):
    path = _dataflow_path(dataflow_id)
    if path is None:
        return jsonify({"error": "Invalid dataflow id"}), 400
    if not path.exists():
        return jsonify({"error": f"No dataflow with id '{dataflow_id}'"}), 404

    try:
        record = json.loads(path.read_text())
    except json.JSONDecodeError:
        return jsonify({"error": "Dataflow file is corrupted"}), 500

    return jsonify({"status": "ok", **record})


@app.put("/api/dataflows/<dataflow_id>")
def save_dataflow(dataflow_id: str):
    """Autosave target - Chart Studio's publish flow has its own explicit
    save, but the canvas itself has no save button, so this is called on a
    debounce every time nodes/edges change (see frontend/src/App.tsx)."""
    path = _dataflow_path(dataflow_id)
    if path is None:
        return jsonify({"error": "Invalid dataflow id"}), 400
    if not path.exists():
        return jsonify({"error": f"No dataflow with id '{dataflow_id}'"}), 404

    payload = request.get_json(silent=True) or {}
    if not isinstance(payload.get("nodes"), list) or not isinstance(payload.get("edges"), list):
        return jsonify({"error": "'nodes' and 'edges' must be arrays"}), 400

    try:
        record = json.loads(path.read_text())
    except json.JSONDecodeError:
        record = {}

    record["id"] = dataflow_id
    record["nodes"] = payload["nodes"]
    record["edges"] = payload["edges"]
    if isinstance(payload.get("name"), str) and payload["name"].strip():
        record["name"] = payload["name"].strip()
    # Optional - omitted on a save that isn't touching the project dataset
    # list leaves whatever was already persisted untouched.
    if isinstance(payload.get("projectDatasets"), list):
        record["projectDatasets"] = payload["projectDatasets"]
    record.setdefault("projectDatasets", [])
    record.setdefault("createdAt", datetime.now(timezone.utc).isoformat())
    record["updatedAt"] = datetime.now(timezone.utc).isoformat()

    _atomic_write_text(path, json.dumps(record))
    return jsonify({"status": "ok", **_dataflow_summary(record)})


@app.patch("/api/dataflows/<dataflow_id>")
def rename_dataflow(dataflow_id: str):
    """Renames a dataflow without touching its nodes/edges - kept separate
    from save_dataflow (PUT) so the Toolbar's rename field doesn't need to
    carry the full canvas state around just to change a name."""
    path = _dataflow_path(dataflow_id)
    if path is None:
        return jsonify({"error": "Invalid dataflow id"}), 400
    if not path.exists():
        return jsonify({"error": f"No dataflow with id '{dataflow_id}'"}), 404

    payload = request.get_json(silent=True) or {}
    name = payload.get("name")
    if not isinstance(name, str) or not name.strip():
        return jsonify({"error": "'name' must be a non-empty string"}), 400

    try:
        record = json.loads(path.read_text())
    except json.JSONDecodeError:
        record = {}

    record["id"] = dataflow_id
    record["name"] = name.strip()
    record.setdefault("nodes", [])
    record.setdefault("edges", [])
    record.setdefault("createdAt", datetime.now(timezone.utc).isoformat())
    record["updatedAt"] = datetime.now(timezone.utc).isoformat()

    _atomic_write_text(path, json.dumps(record))
    return jsonify({"status": "ok", **_dataflow_summary(record)})


@app.delete("/api/dataflows/<dataflow_id>")
def delete_dataflow(dataflow_id: str):
    path = _dataflow_path(dataflow_id)
    if path is None:
        return jsonify({"error": "Invalid dataflow id"}), 400
    if not path.exists():
        return jsonify({"error": f"No dataflow with id '{dataflow_id}'"}), 404

    path.unlink()

    computed_dir = _dataflow_computed_dir(dataflow_id)
    if computed_dir.is_dir():
        shutil.rmtree(computed_dir, ignore_errors=True)

    return jsonify({"status": "ok"})


@app.delete("/api/dataflows/<dataflow_id>/computed/<path:name>")
def delete_computed_dataset(dataflow_id: str, name: str):
    """Deletes one durable computed output (e.g. "A_buildings.geojson") from
    this dataflow's data/dataflows/{dataflow_id}_computed/ dir - unlike the
    catalog (shared, read-only source data), a computed dataset is owned by
    this dataflow, so "remove from project" on one actually deletes it: a
    View/Interaction ref still pointing at "computed/{name}" will then fail
    to resolve, which is the correct signal that it's gone."""
    if not DATAFLOW_ID_RE.match(dataflow_id):
        return jsonify({"status": "error", "error": "Invalid dataflow id"}), 400

    def _resolve_within(base_dir: Path) -> Path | None:
        candidate = (base_dir / name).resolve()
        try:
            candidate.relative_to(base_dir.resolve())
        except ValueError:
            return None
        return candidate

    computed_path = _resolve_within(_dataflow_computed_dir(dataflow_id))
    if computed_path is None:
        return jsonify({"status": "error", "error": "Invalid name"}), 400

    removed = False
    if computed_path.is_file():
        computed_path.unlink()
        removed = True

    # extract-data-layer also writes a served/vector mirror alongside the
    # durable computed copy (see extract_data_layer) - remove it too, or
    # serve_vector's served-fallback would keep handing out the stale file.
    served_path = _resolve_within(vector_subdir)
    if served_path is not None and served_path.is_file():
        served_path.unlink()
        removed = True

    return jsonify({"status": "ok", "removed": removed})


@app.post("/api/infer-filetype")
def infer_filetype():
    payload = request.get_json(silent=True) or {}

    ref_keys = ["ref", "ref_base", "ref_comp"]
    ref = None

    for key in ref_keys:
        if key in payload and payload[key]:
            ref = payload[key]
            break

    if not ref:
        return jsonify({"ok": False, "error": "missing ref"}), 400
    
    result = {
        "ok": True,
        "ref": ref,
        "kind": None,       # "vector" | "raster" | None
        "is_dir": None,     # bool | None
        "file_type": None,        # ".geojson" | ".png" | etc | None
        "path": None,       # optional debug
    }

    vector_path = next(vector_subdir.glob(f"{ref}.*"), None)
    if vector_path is not None:
        return jsonify({
            "ok": True,
            "kind": "vector",
            "is_dir": False,
            "file_type": vector_path.suffix.lower(),
        }), 200
    
    # -------------------------
    # 2) Raster (file OR directory)
    # -------------------------

    # Case 1: direct file match (e.g., A.tif)
    raster_file = next(raster_subdir.glob(f"{ref}.*"), None)
    if raster_file is not None and raster_file.is_file():
        return jsonify({
            "ok": True,
            "kind": "raster",
            "is_dir": False,
            "file_type": raster_file.suffix.lower(),
        }), 200


    # Case 2: directory match (e.g., raster/A/)
    raster_path = raster_subdir / ref
    if raster_path.exists() and raster_path.is_dir():
        any_file = next((p for p in raster_path.iterdir() if p.is_file()), None)
        ext = any_file.suffix.lower() if any_file else None

        return jsonify({
            "ok": True,
            "kind": "raster",
            "is_dir": True,
            "file_type": ext,
        }), 200

    # -------------------------
    # 3) Not found
    # -------------------------
    return jsonify({
        "ok": True,
        "kind": None,
        "is_dir": None,
        "file_type": None,
    }), 200


@app.get("/api/ai/settings")
def ai_settings_get():
    return jsonify(get_public_settings()), 200


@app.post("/api/ai/settings")
def ai_settings_post():
    payload = request.get_json(silent=True) or {}
    settings = update_settings(payload)
    return jsonify(settings), 200


@app.post("/api/ai/provider-models")
def ai_provider_models():
    payload = request.get_json(silent=True) or {}
    try:
        result = list_provider_models(
            payload.get("apiType"), payload.get("baseUrl"), payload.get("apiKey")
        )
    except ChatError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify(result), 200


@app.post("/api/ai/chat")
def ai_chat():
    payload = request.get_json(silent=True) or {}
    messages = payload.get("messages")
    if not isinstance(messages, list) or not messages:
        return jsonify({"error": "messages must be a non-empty list"}), 400

    try:
        reply = run_chat(messages)
    except ChatError as e:
        return jsonify({"error": str(e)}), 400

    return jsonify({"reply": reply}), 200


if __name__ == '__main__':
    # remove old served before starting
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR, ignore_errors=True)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    vector_subdir.mkdir(parents=True, exist_ok=True)
    raster_subdir.mkdir(parents=True, exist_ok=True)
    metric_subdir.mkdir(parents=True, exist_ok=True)

    # OUT_DIR was just wiped above - bring back every dataflow's computed
    # outputs from their durable per-dataflow copy so a data_layer fetch
    # from before this restart doesn't just vanish.
    _restore_computed_outputs()

    # Start the worker up-front (or you can let send_code_to_worker lazily do it)
    try:
        start_worker()
    except Exception as e:
        print("[WORKER] Failed to start:", e)

    app.run(host='0.0.0.0', port=9797, debug=True)
